name: Run Full Frontend Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Wake backend before frontend tests
      run: |
        echo "Warming up backend"
        curl -f --retry 5 --retry-delay 5 https://skills-tracker-backend.onrender.com/api/skills
    
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit and integration tests
      run: |
          echo "Running UNIT and INTEGRATION tests"
          export PYTHONPATH=.
          pytest -v \
            tests/unit/ \
            tests/integration/ \
            --junitxml=test-results/unit-integration.xml

    - name: Run system tests
      run: |
        echo "Running SYSTEM tests"
        export PYTHONPATH=.
        pytest -v tests/system/ \
          --junitxml=test-results/system.xml

    - name: Run system integration tests
      run: |
        echo "Running SYSTEM INTEGRATION tests"
        export PYTHONPATH=.
        pytest -v tests/system_integration/ \
          --junitxml=test-results/system-integration.xml
